### ISSUE TITLE
Full-Text Extaction, Auto Convert Any Website to Feed and Spam/Similar News Detection Using LLM's

### ISSUE THREAD

**Issue by berkbirkan** [fabriziosalmi/UglyFeed#37]
Hello. Does this script have the rss full-text feature? As you know, rss feeds usually do not include the entire content, instead they include a description. I need a script that will extract the entire content. There are options like morss or fivefilters, but since they do not use LLM technology, I think they are ineffective on some sites. Does your script find a solution to this?

I also need a structure that will record news in the database, understand the same or similar news and eliminate those news. In the same way, it should automatically detect spam news and eliminate them.

Also, if a website does not have a feed, it should be able to automatically create a feed (again using LLM). If it does not have these features, I would be very happy if you could add them. I can even buy them for a fee because I need them very much.

I would be very happy if you could help me. Thank you for your help.

**Comment by fabriziosalmi** [comment]
Hi, since it potentially a punished crime to extract content from news website and make it avail in other forms I avoided such feature. You can, in some ways, achieve that mission level by using RSSHub.
Then you can aggregate, filter, rewrite whatever you want via UglyFeed. If you need to implement in a sort of pipeline I suggest to use the UglyFeed pypi package (`pip install uglyfeed`) and play with it :)

**Comment by fabriziosalmi** [comment]
For the spam filtering just add a bunch of spamming block words to the conf file and give to LLM a filtering cycle before to create the final RSS XML. For example in the prompt you can add: please remove any content if, after a quick analysis, it is recognised as spam with spam score over 70% in a range from 0 to 100%. It can give awesome results!!
